### ISSUE TITLE
More info in the right drawer

### ISSUE THREAD

**Issue by System-Glitch** [n4bb12/celeste-search#3]
This fully working search engine is extremely effective but under-documented.
A lot of possible keywords for the search bar are not specified in the right drawer. I think that adding a notice telling that the following keywords work would be very helpful:
- Item rarity (maybe with a list of available ones)
- Item category (with a list of available ones, mostly for non-native english speakers who don't know the exact english word because of the often slightly off translations)
- Craftable
- Level
- Other keywords I probably missed

**Comment by n4bb12** [comment]
Thanks for your suggestion.

Since the search consists of normal language/words, there is not really any magic syntax that could be documented.

But there are quite a few keywords where I tried to alias as many options as possible. An example for sold items: "vendor", "sold", "buy", "purchase", "shop" or currency: "money", "gold", "coins". You get the idea.

I'll find a way to better document these keywords.

What do you think of separating the sidebar into two tabs, one for options, one for search docs?

**Comment by n4bb12** [comment]
https://deploy-preview-5--celeste-search.netlify.com/

**Comment by System-Glitch** [comment]
By documenting these keywords, I meant simply saying that you can type the item rarity or category for example, which is not explained yet.

This may be asking a bit much but I think that it's fine as it is when using it on a desktop, but a tab would be nice on smartphones.

**Comment by n4bb12** [comment]
Resolved by https://github.com/n4bb12/celeste-search/pull/5
