### ISSUE TITLE
Show all results by default

### ISSUE THREAD

**Issue by System-Glitch** [n4bb12/celeste-search#4]
When the search bar is empty, nothing is shown. And you don't really know what to search. Most of the time you want a list of available items, so you type `*` in the search bar. It's not really intuitive at first, and I knew it only because I searched for info in the right drawer. Most people probably don't do that.

Showing all results when the bar is empty would be more user-friendly.

**Comment by n4bb12** [comment]
I've gotten a similar request to add back the category buttons from the previous version:

![2019-04-25 Screenshot 001](https://user-images.githubusercontent.com/6810177/56743651-44875600-6777-11e9-86c4-394a3754fad6.png)

I would prefer not to show initial results because this would likely violate the game content usage rules which states that using assets is fine "so long as anyone who sees your Item will easily find this notice".

You can always create this yourself by bookmarking https://search.projectceleste.com/?tab=0&search=*

Would the category buttons be a good enough solution? Do you have any alternative ideas?
Thanks in advance 🥇

**Comment by System-Glitch** [comment]
I think that the categories button would clutter the view. It's already so clean. It would also be redundant with the search by item category by typing the name of the category in the search bar.

An alternative idea would be to put the notice inside a fixed (and closable) footer. But it may be tricky to do so without making it intrusive.

**Comment by n4bb12** [comment]
You mean like a cookie banner 😁

**Comment by n4bb12** [comment]
Right now my preferred solution is to support both and provide an option for each:

- Show all results when empty (default: false)
- Show category buttons (default: true)

Then everybody can have their preferred combination. 🎷

**Comment by n4bb12** [comment]
![2019-04-27 Screenshot 001](https://user-images.githubusercontent.com/6810177/56840350-65d76780-6887-11e9-9cea-8f4cd2800ed8.png)

https://5cc38c61d68d940008f46e5c--celeste-search.netlify.com/
